#!/bin/bash
# Script created by Rainer Rössler (roesslerrr-at-web.de)
# License: Free Software (License GPLv3)

# set permissions of leoclient2 machine for a certain user

CONFPATH="/media/localdisk/leoclient2/machines"
MACHINES="`/bin/ls $CONFPATH`"
#echo $MACHINES

for MACHINENAME in $MACHINES 
do
  
  VMPATH="`/bin/cat $CONFPATH/$MACHINENAME`"
  #echo $VMPATH
  
  chmod -R 777 $VMPATH
  chmod -R 755 $VMPATH/defaults
  chmod -R 755 $VMPATH/snapshot-store/base
  chmod 755 $VMPATH/*.vdi
  
done

exit 0
