#!/usr/bin/perl -w
# $Id$
# This Script (run-vm-printer-spooler) was created by Rüdiger Beck
# It is released under the GPL Version 3
# For Bugs send mail to: jeffbeck-at-web.de

# Bibliotheken
use strict;
use Linux::Inotify2;
use File::Basename;
use File::Copy;
use File::Path;
# use log names of perl variables, i.e. $UID
use English;
use Log::Log4perl qw(:easy);

my $config_file = "/etc/leoclient/leoclient-vm-printer.conf";
{package Conf ; do $config_file || die "ERROR: $config_file not found or readable\n"} 

my $home=$ENV{'HOME'};
my $UID_name=getpwuid($UID);
my $EUID_name=getpwuid($EUID);
my ($GID_name)=getgrgid($GID);
my ($EGID_name)=getgrgid($EGID);

# configure logging
my $log="/tmp/run-vm-printer-spooler.log-".$UID_name;
my $script="run-vm-printer-spooler";
# allow everybody to log into the logfile
umask 000;
Log::Log4perl->easy_init({ 
                level   => $DEBUG,
                file    => ">>$log" } );    

INFO "##################################################";
INFO "$script started (pid=$PROCESS_ID)";
INFO "   \$spool_dir_user:  $Conf::spool_dir_user\n";
INFO "   \$final_printed_file_user:  $Conf::final_printed_file_user\n";

&kill_other_scripts();
INFO "\$HOME: $home";
INFO "UID:  $UID_name ($UID)\n";
INFO "EUID: $EUID_name ($EUID)\n";
INFO "GID:  $GID_name ($GID)\n";
INFO "EGID: $EGID_name ($EGID)\n";

############################################################
# Configuration
############################################################
# dir to watch (must be directory)
#OLD: my $dir=$home."/".".ausdruck-winxp-spool";
my $dir=$home."/Home_auf_Server/".$Conf::spool_dir_user;

system("mkdir -p $dir");

#OLD: my $final_file=$home."/"."ausdruck-winxp-fertig.pdf";
my $final_file=$home."/Home_auf_Server/".$Conf::final_printed_file_user;


my $new_home_file="/tmp/heimatverzeichnis";

############################################################
# Script
############################################################
### Define an Inotify2 instance
INFO "Watching:   $dir \n";
if (not -e $dir){
    INFO "Watching $dir does not exist";
    exit;
}
my $inotify = new Linux::Inotify2
or die "Unable to create new inotify object: $!";
$inotify->watch ( $dir, IN_MOVED_TO )
or die "watch creation failed";


my $kidpid = fork();
my $dead_kid=0;
if (not defined $kidpid) {
    print "No resources\n";
} elsif ($kidpid == 0) {
    INFO "Child process started with pid $PROCESS_ID";
    &spooler();
} else {
    INFO "Parent process started with pid $PROCESS_ID";
    &user_change();
    # do not wait for child, kill it
    &kill_other_scripts();
    # wait for child
    #my $dead_kid = waitpid($kidpid,0);
    INFO "Parent process will end now";
}



sub spooler {
    while() {
        my @events = $inotify->read;
        unless ( @events > 0 ) {
            print "read error: $!";
            last;
        }
        foreach( @events ) {
            my $abs_path=$_->fullname;
            if (-f $abs_path){
                # print command goes here instead of "sleep 3" --> "lp $abs_path" 
                INFO "Printing:   $abs_path \n";
                system("lp $abs_path && echo '   ---> Printed successfully' >> $log || echo '   ---> ERROR printing $abs_path' >> $log");
                # moving away file
                INFO "Moving source:     $abs_path\n";
                INFO "       target:     $final_file\n";
                system("mv $abs_path $final_file && echo '   ---> Moved successfully' >> $log || echo '   ---> ERROR moving $abs_path' >> $log");
            }
        }
    }
}



sub user_change{
    while (){
        if (-e "$new_home_file"){
            my $new_home=&get_new_home();
            #INFO "Userchange($PROCESS_ID): $new_home ($home)";
            if ($new_home ne $home){
                INFO "Userchange($PROCESS_ID): user has changed -> terminate";
                return;
            } else {
                # INFO "Userchange($PROCESS_ID): user unchanged -> waiting";
            }
        } else {
            INFO "Userchange($PROCESS_ID): cannot read $new_home_file";
        }
        sleep 5;
    }
}






sub kill_other_scripts {    
    INFO "Killing all other scripts:";
    my $pid_string=`pgrep -f $script`;
    my (@pids) = split("\n",$pid_string);
    foreach my $pid (@pids){
        if (not $pid==$PROCESS_ID){
            my $string=`ps -o cmd= -p $pid`;
            if ($string=~/perl/){
                # make sure its the script
                INFO "Killing $script with $pid";
                system("kill $pid && echo '   ---> Killed succesfully' >> $log || echo '   ---> ERROR killing $pid' >> $log");
            } else {
                INFO "NOT Killing $string";
            }
        }
    }
}



sub get_new_home{
    my $new_home=`cat $new_home_file`;
    chomp($new_home);
    return $new_home;
}
